#!/bin/bash

echo "🚀 AZURE CLI ENVIRONMENT SETUP (Alternative to Portal)"
echo "====================================================="

echo ""
echo "If you prefer using Azure CLI instead of the portal, run these commands:"
echo ""
echo "# First, login to Azure CLI (if not already logged in):"
echo "az login"
echo ""
echo "# Set the essential environment variables for API service:"
echo "az webapp config appsettings set --resource-group [YOUR_RESOURCE_GROUP] --name campuspe-api-staging --settings \\"
echo "  NODE_ENV=production \\"
echo "  PORT=8080 \\"
echo "  HOST=0.0.0.0 \\"
echo "  JWT_SECRET=campuspe_super_secret_jwt_key_2025 \\"
echo "  CORS_ORIGIN=https://campuspe-web-staging-erd8dvb3ewcjc5g2.southindia-01.azurewebsites.net \\"
echo "  MONGODB_URI='mongodb+srv://CampusPeAdmin:CampusPe@campuspestaging.adsljpw.mongodb.net/campuspe?retryWrites=true&w=majority&appName=CampuspeStaging'"
echo ""
echo "# After running the command, test the API:"
echo "curl -I https://campuspe-api-staging-hmfjgud5c6a7exe9.southindia-01.azurewebsites.net/health"
echo ""
echo "⚠️  NOTE: Replace [YOUR_RESOURCE_GROUP] with your actual Azure resource group name"
echo ""
