#!/bin/bash
# Azure Environment Variable Fix Script
# Run this to update Azure App Service environment variables

echo "=== CampusPe Web - Azure Environment Variable Configuration ==="
echo ""
echo "CRITICAL FIXES NEEDED in Azure Portal:"
echo ""
echo "1. Update PORT from 80 to 8080:"
echo "   - Go to Azure Portal > campuspe-web-staging > Environment variables"
echo "   - Change PORT from '80' to '8080'"
echo ""
echo "2. Update NEXT_PUBLIC_API_URL to include region suffix:"
echo "   - Change from: campuspe-api-staging.azurewebsites.net"
echo "   - Change to: https://campuspe-api-staging-hmfjgud5c6a7exe9.southindia-01.azurewebsites.net"
echo ""
echo "3. Ensure NODE_ENV is set to 'production'"
echo ""
echo "Current detected issues based on your environment variables:"
echo "❌ PORT=80 (should be 8080 for Node.js apps)"
echo "❌ NEXT_PUBLIC_API_URL missing region-specific suffix"
echo ""
echo "After making these changes:"
echo "1. Click 'Apply' in Azure Portal"
echo "2. Wait for app to restart (2-3 minutes)"
echo "3. Test the website again"
echo ""
echo "Alternative: You can also set these via Azure CLI:"
echo "az webapp config appsettings set --resource-group [your-resource-group] --name campuspe-web-staging --settings PORT=8080"
echo "az webapp config appsettings set --resource-group [your-resource-group] --name campuspe-web-staging --settings NEXT_PUBLIC_API_URL=https://campuspe-api-staging-hmfjgud5c6a7exe9.southindia-01.azurewebsites.net"
