#!/bin/bash

echo "🚀 Azure App Service Creation Guide for Frontend"
echo "==============================================="
echo ""

echo "📋 STEP-BY-STEP AZURE PORTAL SETUP"
echo ""

echo "1️⃣ CREATE NEW APP SERVICE"
echo "========================="
echo "• Go to: https://portal.azure.com"
echo "• Click: Create a resource"
echo "• Search: Web App"
echo "• Click: Create"
echo ""

echo "2️⃣ BASIC CONFIGURATION"
echo "======================"
echo "Subscription: [Your Azure Subscription]"
echo "Resource Group: [Same as your API - likely 'campuspe' or similar]"
echo "Name: campuspe-web-staging-new"
echo "Publish: Code"
echo "Runtime Stack: Node 20 LTS"
echo "Operating System: Linux"
echo "Region: South India (same as your API)"
echo "Pricing Plan: [Choose your preferred plan - B1 Basic or higher]"
echo ""

echo "3️⃣ DEPLOYMENT CONFIGURATION"
echo "============================"
echo "• Go to newly created app → Deployment Center"
echo "• Source: GitHub"
echo "• Organization: CampusPe"
echo "• Repository: Campuspe_Staging"
echo "• Branch: main"
echo "• Build Provider: GitHub Actions"
echo "• Runtime Stack: Node.js"
echo "• Version: 20 LTS"
echo "• App location: /apps/web"
echo "• Api location: [Leave empty]"
echo "• Output location: .next"
echo ""

echo "4️⃣ ENVIRONMENT VARIABLES"
echo "========================"
echo "• Go to: Configuration → Environment Variables"
echo "• Add these variables:"
echo ""
echo "NEXT_PUBLIC_API_URL=https://campuspe-api-staging-hmfjgud5c6a7exe9.southindia-01.azurewebsites.net"
echo "NODE_ENV=production"
echo "WEBSITE_NODE_DEFAULT_VERSION=20.x"
echo "SCM_DO_BUILD_DURING_DEPLOYMENT=true"
echo ""

echo "5️⃣ CONFIGURATION SETTINGS"
echo "========================="
echo "• Go to: Configuration → General Settings"
echo "• Platform: 64 Bit"
echo "• FTP state: Disabled"
echo "• HTTP version: 2.0"
echo "• Web sockets: Off"
echo "• Always On: On (if available)"
echo "• Startup Command: node startup.js"
echo ""

echo "✅ NEW APP SERVICE DETAILS:"
echo "========================="
echo "New URL will be: https://campuspe-web-staging-new.azurewebsites.net"
echo "Working API URL: https://campuspe-api-staging-hmfjgud5c6a7exe9.southindia-01.azurewebsites.net"
