#!/bin/bash

echo "🔍 Diagnosing 503 Service Unavailable Error"
echo "=========================================="

echo ""
echo "🚨 CURRENT STATUS: Application deployed but not starting"
echo ""

echo "📋 IMMEDIATE ACTIONS REQUIRED:"
echo ""
echo "1. ⚙️  SET ENVIRONMENT VARIABLES IN AZURE PORTAL"
echo "   Go to: https://portal.azure.com"
echo "   Navigate: App Services → campuspe-web-staging → Configuration → Application settings"
echo ""
echo "   ADD THESE 6 VARIABLES:"
echo "   ┌─────────────────────────────────────────────────────────────────────────┐"
echo "   │ PORT = 8080                                                             │"
echo "   │ NODE_ENV = production                                                   │"
echo "   │ NEXT_PUBLIC_API_URL = https://campuspe-api-staging-hmfjgud5c6a7exe9.southindia-01.azurewebsites.net │"
echo "   │ WEBSITES_ENABLE_APP_SERVICE_STORAGE = false                            │"
echo "   │ WEBSITE_RUN_FROM_PACKAGE = 1                                           │"
echo "   │ NEXT_TELEMETRY_DISABLED = 1                                            │"
echo "   └─────────────────────────────────────────────────────────────────────────┘"
echo ""
echo "   ⚠️  CRITICAL: Click 'SAVE' after adding all variables!"
echo ""

echo "2. 🔄 RESTART THE SERVICE"
echo "   In same Azure Portal page: Overview → Restart button → Confirm"
echo ""

echo "3. 📊 CHECK AZURE LOGS"
echo "   Azure Portal → campuspe-web-staging → Monitoring → Log stream"
echo "   Watch for startup messages and errors"
echo ""

echo "4. ⏱️  WAIT FOR STARTUP"
echo "   Allow 2-3 minutes for the service to fully restart"
echo ""

echo "📝 COMMON 503 ERROR CAUSES:"
echo "┌─────────────────────────────────────────────────────────────────┐"
echo "│ ❌ Missing environment variables (80% of cases)                   │"
echo "│ ❌ Application startup script failure                             │"
echo "│ ❌ Port binding issues                                            │"
echo "│ ❌ Node.js process crashed on startup                             │"
echo "│ ❌ Missing dependencies or build artifacts                        │"
echo "└─────────────────────────────────────────────────────────────────┘"
echo ""

echo "🧪 TESTING COMMANDS:"
echo ""
echo "Test after fixing:"
echo "curl -I https://campuspe-web-staging-erd8dvb3ewcjc5g2.southindia-01.azurewebsites.net/"
echo ""
echo "Check comprehensive status:"
echo "./comprehensive-test.sh"
echo ""

echo "🆘 IF STILL FAILING AFTER ENVIRONMENT VARIABLES:"
echo "1. Check Azure Portal logs for specific error messages"
echo "2. Verify startup.js/startup.sh files exist in deployment"
echo "3. Ensure server-azure.js is properly configured"
echo "4. Check if Next.js build artifacts are present"

