#!/bin/bash

echo "🚨 FIXING API 503 ERROR - Environment Variables Missing"
echo "======================================================"

echo ""
echo "🔍 PROBLEM IDENTIFIED:"
echo "   The API service is deployed but failing to start because"
echo "   essential environment variables are missing in Azure Portal."
echo ""

echo "📋 REQUIRED ACTIONS:"
echo ""
echo "1. 🌐 GO TO AZURE PORTAL"
echo "   URL: https://portal.azure.com"
echo "   Navigate: App Services → campuspe-api-staging → Configuration → Application settings"
echo ""

echo "2. ⚙️  ADD THESE ENVIRONMENT VARIABLES:"
echo ""
echo "   Click 'New application setting' and add each of these:"
echo ""
echo "┌─────────────────────────────────────────────────────────────────────────────────────────┐"
echo "│ ESSENTIAL VARIABLES (Required for startup):                                               │"
echo "├─────────────────────────────────────────────────────────────────────────────────────────┤"
echo "│ Name: NODE_ENV                                                                             │"
echo "│ Value: production                                                                          │"
echo "├─────────────────────────────────────────────────────────────────────────────────────────┤"
echo "│ Name: PORT                                                                                 │"
echo "│ Value: 8080                                                                                │"
echo "├─────────────────────────────────────────────────────────────────────────────────────────┤"
echo "│ Name: HOST                                                                                 │"
echo "│ Value: 0.0.0.0                                                                             │"
echo "├─────────────────────────────────────────────────────────────────────────────────────────┤"
echo "│ Name: MONGODB_URI                                                                          │"
echo "│ Value: mongodb+srv://CampusPeAdmin:CampusPe@campuspestaging.adsljpw.mongodb.net/campuspe?retryWrites=true&w=majority&appName=CampuspeStaging │"
echo "├─────────────────────────────────────────────────────────────────────────────────────────┤"
echo "│ Name: JWT_SECRET                                                                           │"
echo "│ Value: campuspe_super_secret_jwt_key_2025                                                  │"
echo "├─────────────────────────────────────────────────────────────────────────────────────────┤"
echo "│ Name: CORS_ORIGIN                                                                          │"
echo "│ Value: https://campuspe-web-staging-erd8dvb3ewcjc5g2.southindia-01.azurewebsites.net      │"
echo "└─────────────────────────────────────────────────────────────────────────────────────────┘"
echo ""

echo "3. 💾 SAVE CONFIGURATION"
echo "   ⚠️  CRITICAL: Click 'SAVE' button after adding all variables!"
echo "   Azure will automatically restart the service."
echo ""

echo "4. ⏱️  WAIT FOR RESTART"
echo "   Allow 2-3 minutes for the API service to restart with new variables."
echo ""

echo "5. 🧪 TEST THE FIX"
echo "   Run this command to test if API is working:"
echo "   curl -I https://campuspe-api-staging-hmfjgud5c6a7exe9.southindia-01.azurewebsites.net/health"
echo ""

echo "🎯 EXPECTED RESULT AFTER FIX:"
echo "   HTTP/1.1 200 OK"
echo "   Content-Type: application/json"
echo ""

echo "🔗 QUICK LINKS:"
echo "   • Azure Portal: https://portal.azure.com"
echo "   • API Service: campuspe-api-staging"
echo "   • Web App: https://campuspe-web-staging-erd8dvb3ewcjc5g2.southindia-01.azurewebsites.net"
echo ""

echo "📞 AFTER FIXING API, RUN:"
echo "   ./test-cors-fix.sh    # Test CORS configuration"
echo "   ./comprehensive-test.sh    # Full system test"
