#!/bin/bash

echo "🚨 Azure Deployment Diagnosis & Fix"
echo "=================================="
echo ""

echo "🔍 Common Azure App Service Deployment Issues:"
echo ""
echo "1️⃣ Missing required environment variables"
echo "2️⃣ Incorrect startup commands"
echo "3️⃣ Node.js build failures"
echo "4️⃣ Package.json dependencies issues"
echo ""

echo "🔧 Required Environment Variables for Azure:"
echo ""
echo "# Database & Core"
echo "MONGODB_URI=mongodb+srv://username:password@cluster.mongodb.net/campuspe-staging"
echo "PORT=8080"
echo "NODE_ENV=production"
echo "JWT_SECRET=your-jwt-secret"
echo ""

echo "# WABB Configuration (CORRECTED)"
echo "WABB_API_KEY=your-wabb-api-key"
echo "WABB_WEBHOOK_URL=https://api.wabb.in/api/v1/webhooks-automation/catch/220/HJGMsTitkl8a/"
echo "WABB_WEBHOOK_URL_RESUME=https://api.wabb.in/api/v1/webhooks-automation/catch/220/ORlQYXvg8qk9/"
echo "API_BASE_URL=https://campuspe-api-staging.azurewebsites.net"
echo ""

echo "# AI Services"
echo "CLAUDE_API_KEY=your-claude-api-key"
echo "ANTHROPIC_API_KEY=your-anthropic-api-key"
echo ""

echo "# CORS"
echo "CORS_ORIGIN=https://dev.campuspe.com,https://campuspe-web-staging-erd8dvb3ewcjc5g2.southindia-01.azurewebsites.net,http://localhost:3000"
echo ""

echo "🛠️ Deployment Fix Steps:"
echo ""
echo "1. Check package.json startup script:"
echo "   - Ensure 'start' script is set to 'node server.js'"
echo ""
echo "2. Verify all environment variables are set in Azure:"
echo "   - Go to Azure Portal → campuspe-api-staging → Configuration"
echo "   - Add missing variables above"
echo ""
echo "3. Check Azure deployment logs:"
echo "   - Go to Azure Portal → campuspe-api-staging → Deployment Center"
echo "   - View latest deployment logs for errors"
echo ""
echo "4. Manual deployment test:"
echo "   - Try deploying from GitHub Actions again"
echo "   - Or use Azure CLI deployment"
echo ""

echo "🧪 Test After Fix:"
echo "curl https://campuspe-api-staging.azurewebsites.net/api/health"
echo ""

echo "📋 Priority Actions:"
echo "1. Set MONGODB_URI with actual credentials"
echo "2. Set WABB_API_KEY with real key"
echo "3. Set CLAUDE_API_KEY/ANTHROPIC_API_KEY"
echo "4. Restart Azure App Service"
