#!/bin/bash

echo "🔄 GitHub Actions Deployment Setup Guide"
echo "========================================"
echo ""

echo "📋 CHECKLIST: Converting from ZIP to GitHub Actions"
echo ""

echo "✅ 1. AZURE PORTAL CONFIGURATION"
echo "================================"
echo ""
echo "🔸 For API App Service (campuspe-api-staging):"
echo "   → Go to: https://portal.azure.com"
echo "   → Search: campuspe-api-staging"
echo "   → Deployment Center → Source: GitHub"
echo "   → Repository: CampusPe/Campuspe_Staging"
echo "   → Branch: main"
echo "   → Build Provider: GitHub Actions"
echo "   → App location: /apps/api"
echo "   → Output location: dist"
echo ""
echo "🔸 For Web App Service (campuspe-web-staging):"
echo "   → Go to: https://portal.azure.com"
echo "   → Search: campuspe-web-staging"
echo "   → Deployment Center → Source: GitHub"
echo "   → Repository: CampusPe/Campuspe_Staging"
echo "   → Branch: main"
echo "   → Build Provider: GitHub Actions"
echo "   → App location: /apps/web"
echo "   → Output location: .next"
echo ""

echo "✅ 2. GITHUB SECRETS VERIFICATION"
echo "================================="
echo ""
echo "🔸 Go to: https://github.com/CampusPe/Campuspe_Staging/settings/secrets/actions"
echo ""
echo "Required secrets for API:"
echo "   • AZUREAPPSERVICE_CLIENTID_8A6DED1EC9FF4D6DBF9BC09565C923D6"
echo "   • AZUREAPPSERVICE_TENANTID_6F962B613A624D3582F2985BCDA08CE8"
echo "   • AZUREAPPSERVICE_SUBSCRIPTIONID_AE3ECD9C02CC4AD296820DF8B2D5C91F"
echo ""
echo "Required secrets for WEB:"
echo "   • AZUREAPPSERVICE_CLIENTID_10A48428474E493691C9C84DDB40001E"
echo "   • AZUREAPPSERVICE_TENANTID_79127984E4DA42A294BB73FFB593F0AD"
echo "   • AZUREAPPSERVICE_SUBSCRIPTIONID_6DB71F4C43254DB199DC1698EE4631D0"
echo ""

echo "✅ 3. ENVIRONMENT VARIABLES"
echo "==========================="
echo ""
echo "🔸 For Web App (campuspe-web-staging):"
echo "   → Configuration → Environment Variables"
echo "   → Add: NEXT_PUBLIC_API_URL=https://campuspe-api-staging-hmfjgud5c6a7exe9.southindia-01.azurewebsites.net"
echo "   → Add: NODE_ENV=production"
echo ""

echo "✅ 4. WORKFLOW FILES STATUS"
echo "==========================="
echo ""
echo "API Workflow: .github/workflows/main_campuspe-api-staging.yml"
if [ -f ".github/workflows/main_campuspe-api-staging.yml" ]; then
    echo "   ✅ EXISTS"
else
    echo "   ❌ MISSING"
fi
echo ""
echo "Web Workflow: .github/workflows/main_campuspe-web-staging.yml"
if [ -f ".github/workflows/main_campuspe-web-staging.yml" ]; then
    echo "   ✅ EXISTS"
else
    echo "   ❌ MISSING"
fi
echo ""

echo "✅ 5. TEST DEPLOYMENT"
echo "===================="
echo ""
echo "After completing Azure configuration:"
echo "   1. Make a small change to apps/api/src/app.ts"
echo "   2. Make a small change to apps/web/pages/index.tsx"
echo "   3. Commit and push to main branch"
echo "   4. Check GitHub Actions: https://github.com/CampusPe/Campuspe_Staging/actions"
echo "   5. Verify deployments complete successfully"
echo ""

echo "🎯 NEXT STEPS:"
echo "=============="
echo "1. Complete Azure Portal configuration above"
echo "2. Verify GitHub secrets are present"
echo "3. Push a test change to trigger deployments"
echo "4. Monitor GitHub Actions for success"
echo ""

echo "💡 TROUBLESHOOTING:"
echo "=================="
echo "• If deployments fail, check GitHub Actions logs"
echo "• Ensure Azure service principals have correct permissions"
echo "• Verify environment variables are set in Azure"
echo "• Check that runtime stack is Node 20 LTS in Azure"
