#!/bin/bash

echo "🎯 POST-SETUP INSTRUCTIONS: After Creating New App Service"
echo "=========================================================="
echo ""

echo "📝 AFTER YOU CREATE THE NEW APP SERVICE, DO THESE STEPS:"
echo ""

echo "1️⃣ GET THE NEW APP SERVICE SECRETS"
echo "=================================="
echo "• In Azure Portal, go to your new app: campuspe-web-staging-new"
echo "• Go to: Deployment Center → GitHub Actions"
echo "• Azure will show you the secrets that need to be added to GitHub"
echo "• Copy these 3 secret values:"
echo "  - Client ID"
echo "  - Tenant ID" 
echo "  - Subscription ID"
echo ""

echo "2️⃣ ADD SECRETS TO GITHUB"
echo "========================"
echo "• Go to: https://github.com/CampusPe/Campuspe_Staging/settings/secrets/actions"
echo "• Click: New repository secret"
echo "• Add these 3 secrets with the values from Azure:"
echo ""
echo "Secret Name: AZUREAPPSERVICE_CLIENTID_NEW_WEB"
echo "Secret Name: AZUREAPPSERVICE_TENANTID_NEW_WEB"
echo "Secret Name: AZUREAPPSERVICE_SUBSCRIPTIONID_NEW_WEB"
echo ""

echo "3️⃣ REMOVE OLD WORKFLOW FILE"
echo "============================"
echo "• Delete the old workflow file:"
echo "• File to delete: .github/workflows/main_campuspe-web-staging.yml"
echo ""

echo "4️⃣ PUSH CHANGES TO TRIGGER DEPLOYMENT"
echo "====================================="
echo "• The new workflow is ready: .github/workflows/main_campuspe-web-staging-new.yml"
echo "• API CORS is updated to allow new domain"
echo "• Commit and push all changes"
echo ""

echo "5️⃣ TEST THE NEW DEPLOYMENT"
echo "=========================="
echo "• Check GitHub Actions: https://github.com/CampusPe/Campuspe_Staging/actions"
echo "• New app URL: https://campuspe-web-staging-new.azurewebsites.net"
echo "• API should work with new frontend"
echo ""

echo "🚨 IMPORTANT NOTES:"
echo "=================="
echo "• Make sure to set all environment variables in the new app service"
echo "• The startup command should be: node startup.js"
echo "• Runtime stack: Node 20 LTS"
echo "• The new app will have a clean GitHub Actions setup from the start"
echo ""

echo "✅ VERIFICATION CHECKLIST:"
echo "========================="
echo "□ New app service created with name: campuspe-web-staging-new"
echo "□ GitHub Actions configured in Azure Deployment Center"
echo "□ 3 secrets added to GitHub repository"
echo "□ Environment variables set in Azure app configuration"
echo "□ Old workflow file deleted"
echo "□ Changes committed and pushed"
echo "□ GitHub Actions workflow running successfully"
echo "□ New app URL accessible and working"
