name: Deploy Web to Azure Web App

on:
  push:
    branches: [ main ]
    paths: [ 'apps/web/**' ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: apps/web/package-lock.json

      - name: Install dependencies
        run: |
          cd apps/web
          npm ci

      - name: Build application
        run: |
          cd apps/web
          npm run build

      - name: Create deployment package
        run: |
          cd apps/web
          
          # Create deployment directory
          mkdir -p deploy
          
          # Copy all necessary files for Next.js
          cp -r .next/ deploy/
          cp -r public/ deploy/
          cp package.json deploy/
          cp package-lock.json deploy/
          cp next.config.js deploy/
          
          # Create web.config for Azure with Next.js configuration
          cat > deploy/web.config << 'EOF'
          <?xml version="1.0" encoding="utf-8"?>
          <configuration>
            <system.webServer>
              <handlers>
                <add name="iisnode" path="server.js" verb="*" modules="iisnode"/>
              </handlers>
              <rewrite>
                <rules>
                  <rule name="StaticContent" stopProcessing="true">
                    <match url="^(_next/static|favicon\.ico|robots\.txt|sitemap\.xml)" />
                    <action type="None" />
                  </rule>
                  <rule name="DynamicContent">
                    <conditions>
                      <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="True"/>
                    </conditions>
                    <action type="Rewrite" url="server.js"/>
                  </rule>
                </rules>
              </rewrite>
              <iisnode node_env="production" />
            </system.webServer>
          </configuration>
          EOF
          
          # Create server.js for Azure deployment
          cat > deploy/server.js << 'EOF'
          const { createServer } = require('http')
          const { parse } = require('url')
          const next = require('next')

          const dev = process.env.NODE_ENV !== 'production'
          const hostname = process.env.WEBSITE_HOSTNAME || 'localhost'
          const port = process.env.PORT || 3000

          const app = next({ dev, hostname, port })
          const handle = app.getRequestHandler()

          app.prepare().then(() => {
            createServer(async (req, res) => {
              try {
                const parsedUrl = parse(req.url, true)
                await handle(req, res, parsedUrl)
              } catch (err) {
                console.error('Error occurred handling', req.url, err)
                res.statusCode = 500
                res.end('internal server error')
              }
            }).listen(port, (err) => {
              if (err) throw err
              console.log(`> Ready on http://${hostname}:${port}`)
            })
          })
          EOF

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'campuspe-web-staging'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEB_PUBLISH_PROFILE }}
          package: apps/web/deploy
