name: Deploy API to Azure Web App

on:
  push:
    branches: [ main ]
    paths: [ 'apps/api/**' ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: apps/api/package-lock.json

      - name: Install dependencies
        run: |
          cd apps/api
          npm ci --include=dev

      - name: Build application
        run: |
          cd apps/api
          npm run build

      - name: Create deployment package
        run: |
          cd apps/api
          
          # Create deployment directory
          mkdir -p deploy
          
          # Copy built application
          cp -r dist/ deploy/
          
          # Copy package files
          cp package.json deploy/
          cp package-lock.json deploy/
          
          # Install ONLY production dependencies in deploy folder
          cd deploy
          npm ci --production --ignore-scripts
          cd ..
          
          # Create startup script
          cat > deploy/startup.sh << 'EOF'
#!/bin/bash
echo "🚀 Starting CampusPe API..."
echo "📦 Node.js version: $(node --version)"
cd /home/site/wwwroot
export NODE_ENV=production
export PORT=${PORT:-8080}
node dist/app.js
EOF
          chmod +x deploy/startup.sh

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'campuspe-api-staging-hmfjgud5c6a7exe9'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_API_PUBLISH_PROFILE }}
          package: apps/api/deploy
