name: Deploy API to Azure Web App

on:
  push:
    branches: [ main ]
    paths: [ 'apps/api/**' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: apps/api/package-lock.json

      - name: Install dependencies
        run: |
          cd apps/api
          npm ci

      - name: Build application
        run: |
          cd apps/api
          npm run build

      - name: Create deployment package
        run: |
          cd apps/api
          # Copy all necessary files
          mkdir -p deploy
          cp -r dist/ deploy/
          cp package.json deploy/
          cp package-lock.json deploy/
          # Create web.config for Azure
          cat > deploy/web.config << 'EOF'
          <?xml version="1.0" encoding="utf-8"?>
          <configuration>
            <system.webServer>
              <handlers>
                <add name="iisnode" path="dist/app.js" verb="*" modules="iisnode"/>
              </handlers>
              <rewrite>
                <rules>
                  <rule name="NodeInspector" patternSyntax="ECMAScript" stopProcessing="true">
                    <match url="^app.js\/debug[\/]?" />
                  </rule>
                  <rule name="StaticContent">
                    <action type="Rewrite" url="public{REQUEST_URI}"/>
                  </rule>
                  <rule name="DynamicContent">
                    <conditions>
                      <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="True"/>
                    </conditions>
                    <action type="Rewrite" url="dist/app.js"/>
                  </rule>
                </rules>
              </rewrite>
              <security>
                <requestFiltering>
                  <hiddenSegments>
                    <remove segment="bin"/>
                  </hiddenSegments>
                </requestFiltering>
              </security>
              <httpErrors existingResponse="PassThrough" />
              <iisnode watchedFiles="web.config;*.js"/>
            </system.webServer>
          </configuration>
          EOF
          cd deploy
          zip -r ../../api-deployment.zip .
          
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: api-deployment
          path: api-deployment.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: api-deployment

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'campuspe-api-staging'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_API_PUBLISH_PROFILE }}
          package: api-deployment.zip
