# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - campuspe-web-staging

on:
  push:
    branches:
      - main
    paths:
      - "apps/web/**"
      - ".github/workflows/main_campuspe-web-staging.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install root dependencies
        run: npm ci

      - name: Install Web dependencies
        working-directory: ./apps/web
        run: npm ci

      - name: Build Web application
        working-directory: ./apps/web
        run: |
          echo "Building Next.js application..."
          npm run build
          echo "Build completed. Checking .next directory..."
          ls -la .next/

      - name: Create deployment package
        run: |
          mkdir -p deployment-package

          # Verify build artifacts exist
          if [ ! -d "apps/web/.next" ]; then
            echo "ERROR: .next directory not found! Build failed."
            exit 1
          fi

          # Copy Next.js build artifacts
          echo "Copying Next.js build artifacts..."
          cp -r apps/web/.next deployment-package/
          cp -r apps/web/public deployment-package/

          # Copy essential application files
          echo "Copying application files..."
          cp apps/web/package*.json deployment-package/
          
          # Copy server files (prioritize server-azure.js for Azure deployment)
          if [ -f "apps/web/server-azure.js" ]; then
            cp apps/web/server-azure.js deployment-package/
            echo "Using server-azure.js for Azure deployment"
          elif [ -f "apps/web/server.js" ]; then
            cp apps/web/server.js deployment-package/
            echo "Using server.js for deployment"
          fi
          
          # Copy configuration files
          cp apps/web/next.config.js deployment-package/ 2>/dev/null || echo "No next.config.js found"
          cp apps/web/startup.js deployment-package/ 2>/dev/null || echo "No startup.js found"
          cp apps/web/startup.sh deployment-package/ 2>/dev/null || echo "No startup.sh found"
          cp apps/web/web.config deployment-package/ 2>/dev/null || echo "No web.config found"

          # Install only production dependencies in deployment package
          echo "Installing production dependencies..."
          cd deployment-package
          npm ci --production --silent
          cd ..

          echo "Final deployment package contents:"
          ls -la deployment-package/
          echo "Package size:"
          du -sh deployment-package/

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: deployment-package/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Set Azure App Service Environment Variables
        run: |
          echo "Setting environment variables for Azure App Service..."
          # These will be set via Azure CLI if available, otherwise manually in portal

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "campuspe-web-staging"
          slot-name: "Production"
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_WEB_STAGING }}

      - name: Verify deployment
        run: |
          echo "Deployment completed. Please verify at:"
          echo "https://campuspe-web-staging.azurewebsites.net"
