# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Web to Azure Web App - campuspe-web-staging

on:
  push:
    branches:
      - main
    paths:
      - "apps/web/**"
      - ".github/workflows/main_campuspe-web-staging.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install root dependencies
        run: npm ci

      - name: Install Web dependencies
        working-directory: ./apps/web
        run: npm ci

      - name: Build Web
        working-directory: ./apps/web
        run: npm run build

      - name: Create deployment package
        run: |
          mkdir deployment-package
          cp -r apps/web/.next apps/web/node_modules apps/web/public deployment-package/
          cp apps/web/package.json apps/web/package-lock.json apps/web/startup.sh apps/web/server.js apps/web/next.config.js deployment-package/
          cp apps/web/.env.production deployment-package/ 2>/dev/null || true
          cp apps/web/web.config deployment-package/ 2>/dev/null || true
          chmod +x deployment-package/startup.sh

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: web-app
          path: deployment-package

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: web-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_78049047CCB2468AB61906BC91B9D5E2 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7EDEB41DD16F4709823C929CC48C8894 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_244A34706AC845219DF909AE50BA9009 }}

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "campuspe-web-staging"
          slot-name: "Production"
          package: .