# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Web to Azure Web App - campuspe-web-staging

on:
  push:
    branches:
      - main
    paths:
      - "apps/web/**"
      - ".github/workflows/main_campuspe-web-staging.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install root dependencies
        run: npm ci

      - name: Install Web dependencies
        working-directory: ./apps/web
        run: npm ci

      - name: Debug Web structure
        working-directory: ./apps/web
        run: |
          echo "=== Web app structure ==="
          ls -la
          echo "=== Package.json content ==="
          cat package.json
          echo "=== Node version ==="
          node --version
          echo "=== NPM version ==="
          npm --version

      - name: Build Web app
        working-directory: ./apps/web
        env:
          NEXT_PUBLIC_API_URL: https://campuspe-api-staging.azurewebsites.net/api
        run: |
          echo "Setting environment variables for build..."
          echo "NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL"
          echo "Starting Next.js build..."
          npm run build
          echo "Build completed. Checking output..."
          ls -la .next/ || echo "No .next directory found"

      - name: Create deployment package
        run: |
          # Create deployment package with complete Next.js app
          mkdir deployment-package

          echo "=== Apps/web structure before copy ==="
          ls -la apps/web/

          # Copy the entire web app structure including hidden files (.next)
          # Using . instead of * to include hidden files
          cd apps/web
          cp -r . ../../deployment-package/
          cd ../..

          echo "=== Deployment package structure ==="
          ls -la deployment-package/

          # Verify .next directory exists
          if [ ! -d "deployment-package/.next" ]; then
            echo "❌ Error: .next directory not found in deployment package!"
            echo "Available files in deployment-package:"
            ls -la deployment-package/
            exit 1
          fi

          echo "✅ .next directory found successfully"

          # Remove unnecessary files for production
          rm -rf deployment-package/.env* || true
          rm -rf deployment-package/README.md || true

          # Ensure executable permissions
          chmod +x deployment-package/startup.sh || true

          echo "📦 Final deployment package contents:"
          ls -la deployment-package/

          # Remove unnecessary files for production
          rm -rf deployment-package/.env* || true
          rm -rf deployment-package/README.md || true
          rm -rf deployment-package/tsconfig.json || true

          # Ensure executable permissions
          chmod +x deployment-package/startup.sh

          echo "Deployment package created successfully"
          ls -la deployment-package/

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: web-app
          path: deployment-package

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: web-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_EE222AFA16FA4A5DA06DD5312531E619 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7A15C7020EEA4011BEFA4FD44BD576D8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6C89CA2016E747AB8F7F6250858F9AC3 }}

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "campuspe-web-staging"
          slot-name: "Production"
          package: .
