# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy API to Azure Web App - campuspe-api-staging

on:
  push:
    branches:
      - main
    paths:
      - "apps/api/**"
      - ".github/workflows/main_campuspe-api-staging.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install root dependencies
        run: npm ci

      - name: Install API dependencies
        working-directory: ./apps/api
        run: npm ci

      - name: Build API
        working-directory: ./apps/api
        run: npm run build

      - name: Create deployment package
        run: |
          mkdir deployment-package
          cp -r apps/api/dist deployment-package/
          cp -r apps/api/node_modules deployment-package/
          cp apps/api/package.json deployment-package/
          cp apps/api/package-lock.json deployment-package/

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: api-app
          path: deployment-package

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: api-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8A6DED1EC9FF4D6DBF9BC09565C923D6 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6F962B613A624D3582F2985BCDA08CE8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AE3ECD9C02CC4AD296820DF8B2D5C91F }}

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "campuspe-api-staging"
          slot-name: "Production"
          package: .
