# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - campuspe-web-staging

on:
  push:
    branches:
      - main
    paths:
      - "apps/web/**"
      - ".github/workflows/main_campuspe-web-staging.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install root dependencies
        run: npm ci

      - name: Install Web dependencies
        working-directory: ./apps/web
        run: npm ci

      - name: Build Web application
        working-directory: ./apps/web
        run: npm run build

      - name: Create deployment package
        run: |
          mkdir -p deployment-package

          # Copy Next.js build artifacts
          echo "Copying Next.js build artifacts..."
          cp -r apps/web/.next deployment-package/
          cp -r apps/web/public deployment-package/

          # Copy application files
          echo "Copying application files..."
          cp -r apps/web/package*.json deployment-package/
          cp -r apps/web/node_modules deployment-package/
          cp apps/web/next.config.js deployment-package/ || echo "No next.config.js found"
          cp apps/web/server.js deployment-package/ || echo "No server.js found"
          cp apps/web/startup.js deployment-package/ || echo "No startup.js found"
          cp apps/web/web.config deployment-package/ || echo "No web.config found"

          echo "Deployment package contents:"
          ls -la deployment-package/

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: deployment-package/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "campuspe-web-staging"
          slot-name: "Production"
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_WEB_STAGING }}
